baseURL = "/"
languageCode = "ja"
title = "TAML"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/tamlLogo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"


[[menu.main]]
	name = "事業内容"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "採用情報"
    url = "/recruit/"
    weight = 2

[[menu.main]]
    name = "問い合わせ"
    url = "/contact/"
    weight = 3

[[menu.main]]
    name = "ABOUT"
    url = "/about/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
